### ISSUE TITLE
[Feature request] Support update-image-vars on machines which do not have local copies of images

### ISSUE THREAD

**Issue by OwenTuz** [appvia/artefactor#107]
I'm happy to raise a PR to implement this, but wanted to raise it as a feature request first to see if it is functionality that you would actually like in artefactor.

### Problem

We have the issue described in the README under "Content Adressable Repo Digests" - images are downloaded and pushed from one machine, and deployments happen from another machine which cannot contact the first.

Without publishing a list of 'new' image names from the machine which runs `artefactor publish`, we end up re-implementing the logic of `update-image-vars` in our own deploy scripts to generate the new image names before we pull the images.

This is well-documented and understandable behaviour, and can be worked around - but it would be useful to have `update-image-vars` be able to do this for us.

### Proposal

Add a flag `--from-remote-registry` (or similar) to the `update-image-vars` command. When called, this would read the existing `ARTEFACTOR_IMAGE_VARS` and, for each image:
- If the image was referenced without a SHA digest, simply transform to the new registry name (`update-image-vars` already does this)
- If the image references a specific SHA digest, transform to `<new_registry_name>:repoDigest-<original_SHA>`
- Fetch the manifest from the remote registry and confirm that images with these names/tags exist
- Return the updated image values (as `update-image-vars` already does)

Does that sound reasonable / is this a useful PR for us to submit?

**Comment by lukeab** [comment]
Hi Owen, 
It's been a few months since I was working on this so I may be need to refresh my own memory. 
Lets figure this out, given a machine which has not had images imported, just has the manifests and meta-data file, and has env vars of the required images, if a sha is used, transform it to <new_registry_name>:repoDigest-<original_SHA>
We might want to adjust that since we cant amend the original_sha to the end of a new sha since that would no longer be a content addressable repo digest.
you would need knowledge of the originating images and know how to address them on the new registry, i dont see a way to relate these without maintaining new meta-data outside of the process.
for example
take nginx:latest from docker hub, `nginx:latest@sha256:a93c8a0b0974c967aebe868a186e5c205f4d3bcb5423a56559f2f9599074bbcd`
we then translate this to `new-registry/nginx@sha256:<newsha>`
I think in fact the tag from the original source is also preserved, i'd have to review the code again to check. 
the trouble is, unless the host running this process has the origin and destination sha metadata in the docker local store, it can't relate the two images. If you can point out how to do this without having the source and destination data and explain that to me we can find a way to do this. Otherwise i fear the slightly broken concept of using content addressable sha's to map an image from one registry to another is actually just the wrong approach.

Anyway, let me know what you think.

**Comment by OwenTuz** [comment]
Thanks for replying so quickly.

In essence I think what I'm describing is similar to a dry run mode?
ie, given:
- a list of image names (as `ARTEFACTOR_IMAGE_VARS`)
- a registry URL

Output the names we _would_ have used to upload them (minus the new SHA because we don't know it), and optionally check the remote manifest to see if they actually exist.

... if that makes sense?

Regarding security properties, I agree it's sadly a bit broken and that's just the way things have to work since we can never guarantee SHA consistency across repos.

The existing workaround for that (in artefactor) is to add a tag containing the original SHA digest:
https://github.com/appvia/artefactor/blob/70fe6bfe4e77e26cd80df5f4fcd6db3eb876006b/pkg/docker/docker.go#L88-L91

This is a (necessary) hack but useful and is what lets us download `nginx` if we know the original SHA of `a93c8a0b0974c967aebe868a186e5c205f4d3bcb5423a56559f2f9599074bbcd` without knowing the new SHA.

However as you've pointed out, we also can't verify (on our machine with no other knowledge of the source images) that it's exactly the same image because the tag can be applied by anybody with access and is not actually tied to the content. So it weakens the security proposition quite a bit.

In our case, that's unfortunate but we're willing to place enough trust on the machine which runs `publish` to accept that if it has tagged something as having a SHA, we will believe in it. It's a bit naff but it's slightly better than just running `docker pull` with no SHA at all.

Not everybody will be willing to take that risk, and so I think it's worth asking whether adding this and documenting it is enough, or whether that's adding too many sharp edges.

Overall, I think it would be a useful option but I don't want to add this upstream if you feel that the benefits are not justified by the complexity. It's something we can manage externally to artefactor if needed.

**Comment by lukeab** [comment]
oh amazing, thanks for the PR, i'll review as soon as i have a chance.

**Comment by OwenTuz** [comment]
Closing as per PR - we worked around this and I'm not sure anyone else is interested in this feature, so let's leave it alone. Thanks for the time spent discussing/reviewing.
